"""The project CLI exposes one full-run path and distinct cleanup scopes."""

from pathlib import Path
from unittest.mock import patch

import pytest

from ptm_pipeline.cli import clean, clean_all, clean_init, run, run_dry
from ptm_pipeline.init import copy_template_files


def initialized_project(tmp_path: Path) -> Path:
    for name in ("Snakefile", "ptm_config.yaml", "helpers.py", "ptm.sh"):
        (tmp_path / name).write_text(name)
    return tmp_path


def test_run_and_clean_use_only_the_full_snakemake_target(tmp_path):
    project = initialized_project(tmp_path)
    with patch("ptm_pipeline.cli.subprocess.run") as execute:
        execute.return_value.returncode = 0
        run(project, cores=2)
        run_dry(project)
        clean(project)

    commands = [call.args[0] for call in execute.call_args_list]
    assert all(command[1] == "all" for command in commands)
    assert commands[0][-2:] == ["--cores", "2"]
    assert commands[1][-1] == "--dry-run"
    assert commands[2][-1] == "--delete-all-output"
    assert all(call.kwargs["cwd"] == project for call in execute.call_args_list)


def test_clean_init_preserves_outputs_and_unrelated_files(tmp_path):
    project = initialized_project(tmp_path)
    (project / "PTM_results.h5mu").write_text("result")
    (project / "Makefile").write_text("my own targets\n")
    (project / "src").mkdir()
    (project / "src" / "notes.R").write_text("keep")

    clean_init(project)

    assert not (project / "Snakefile").exists()
    assert not (project / "ptm_config.yaml").exists()
    assert not (project / "helpers.py").exists()
    assert not (project / "ptm.sh").exists()
    assert (project / "PTM_results.h5mu").exists()
    assert (project / "Makefile").exists()
    assert (project / "src" / "notes.R").exists()


def test_clean_all_deletes_outputs_before_initialization_files(tmp_path):
    project = initialized_project(tmp_path)
    output = project / "PTM_results.h5mu"
    output.write_text("result")

    def delete_outputs(command, **kwargs):
        assert command[-1] == "--delete-all-output"
        assert (project / "Snakefile").exists()
        output.unlink()
        return type("Result", (), {"returncode": 0})()

    with patch("ptm_pipeline.cli.subprocess.run", side_effect=delete_outputs):
        clean_all(project)

    assert not output.exists()
    assert not (project / "Snakefile").exists()


def test_clean_init_removes_an_old_generated_makefile(tmp_path):
    project = initialized_project(tmp_path)
    (project / "Makefile").write_text(
        "# PTM Pipeline Makefile\n# Generated by ptm-pipeline init\n"
    )

    clean_init(project)

    assert not (project / "Makefile").exists()


def test_noninteractive_init_refuses_to_overwrite_without_force(tmp_path):
    from ptm_pipeline.cli import init_default

    project = initialized_project(tmp_path)
    with pytest.raises(SystemExit) as error:
        init_default(project, project)
    assert error.value.code == 1
    assert (project / "ptm_config.yaml").read_text() == "ptm_config.yaml"


def test_template_copy_does_not_create_a_makefile(tmp_path):
    (tmp_path / "Makefile").write_text(
        "# PTM Pipeline Makefile\n# Generated by ptm-pipeline init\n"
    )
    with patch("ptm_pipeline.init.copy_shell_wrapper", return_value=["ptm.sh"]):
        copied = copy_template_files(tmp_path)
    assert copied == ["Snakefile", "helpers.py", "ptm.sh"]
    assert not (tmp_path / "Makefile").exists()
