"""Remove only the files created by project initialization."""

from pathlib import Path

import yaml
from rich.console import Console

console = Console()

INIT_FILES = ("ptm_config.yaml", "Snakefile", "helpers.py", "ptm.sh")
GENERATED_MAKEFILE_HEADER = "# PTM Pipeline Makefile\n# Generated by ptm-pipeline init"


def output_directory(project_dir: Path) -> Path:
    """Locate the configured output tree without allowing cleanup of DEA inputs."""
    project_dir = project_dir.resolve()
    config = yaml.safe_load((project_dir / "ptm_config.yaml").read_text())
    if not isinstance(config, dict) or "dir_out" not in config:
        raise ValueError("ptm_config.yaml must define dir_out")
    if not isinstance(config["dir_out"], str):
        raise TypeError("dir_out must be a string")
    output = (project_dir / config["dir_out"]).resolve()
    if output == project_dir or project_dir not in output.parents:
        raise ValueError("dir_out must be inside the project, separate from its root")
    for name in ("phospho_dea_dir", "protein_dea_dir"):
        if name in config:
            dea = (project_dir / config[name]).resolve()
            if dea == output or output in dea.parents or dea in output.parents:
                raise ValueError(f"dir_out would remove {name}")
    return output


def generated_makefile(project_dir: Path) -> Path | None:
    """Recognize an older Makefile copied by this package."""
    path = project_dir / "Makefile"
    if path.is_file() and path.read_bytes().startswith(
        GENERATED_MAKEFILE_HEADER.encode()
    ):
        return path
    return None


def clean_project(project_dir: Path) -> bool:
    """Delete initialization files, including a recognized legacy Makefile."""
    project_dir = project_dir.resolve()
    if not project_dir.is_dir():
        console.print(f"[red]Project directory does not exist:[/red] {project_dir}")
        return False

    files = [
        project_dir / name for name in INIT_FILES if (project_dir / name).is_file()
    ]
    legacy_makefile = generated_makefile(project_dir)
    if legacy_makefile is not None:
        files.append(legacy_makefile)
    if not files:
        console.print("No initialization files found.")
        return True

    for path in files:
        try:
            path.unlink()
        except OSError as error:
            console.print(f"[red]Could not remove {path}:[/red] {error}")
            return False
        console.print(f"Removed: {path.name}")
    return True
